### ISSUE TITLE
ARM fully supported?

### ISSUE THREAD

**Issue by Mathnerd314** [google/EXEgesis#10]
The [top-level README](https://github.com/google/EXEgesis#whats-next) says ARM Cortex is "underway", but the [tools README](https://github.com/google/EXEgesis/blob/ca6ab91c0e1f617881a34c8e794ea37466229590/exegesis/tools/README.md#arm-a64) lists 4 supported versions of the XML data. Is there more work left to do on ARM or is the top-level README out of date?

**Comment by ondrasej** [comment]
I'm sorry, the README was out of date, and we did not extend the parser to other ARM XML files.
