### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by nateozem** [google/EXEgesis#5]
My build failed for "missing dependency declarations".
I did the following:

* installed `bazel`
* clone repo
* change directory to repo
* then lastly

```
$ bazel build //exegesis/tools:parse_sdm -c opt
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_user/f8a4e05608f194d30caf1f6a29617bdb/external/utf_archive/BUILD.bazel:1:1: undeclared inclusion(s) in rule '@utf_archive//:utf':
this rule is missing dependency declarations for the following files included by 'external/utf_archive/libutf/runestrncmp.c':
  '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include/stdarg.h'.
warning: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Wunknown-warning-option]
1 warning generated.
Target //exegesis/tools:parse_sdm failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.370s, Critical Path: 1.66s


$ bazel help startup_options
[bazel release 0.4.5-homebrew]
```

What may I have done wrong?

**Comment by legrosbuffle** [comment]
This looks like an issue with your clang/Xcode installation. The header is supposed to be provided by clang itself.

Does the file exist ? If yes, you might want to try [disabling sandboxing](https://bazel.build/versions/master/docs/bazel-user-manual.html#sandboxing) with:

`bazel build //exegesis/tools:parse_sdm -c opt --spawn_strategy=standalone`

**Comment by legrosbuffle** [comment]
Maybe also see [this issue](https://github.com/bazelbuild/bazel/issues/2171) in the bazel repo.

**Comment by gchatelet** [comment]
@nateozem please reopen if deemed necessary.

**Comment by nateozem** [comment]
Apologize for not updating this issue. @legrosbuffle was right. It seems to be a `bazel` issue (https://github.com/bazelbuild/bazel/issues/803). No need to reopen. I'm sure that once I fix my setup with `bazel`, my build for this project should work.
