### ISSUE TITLE
Provide Example of Generating min_latency, max_latency, etc

### ISSUE THREAD

**Issue by samuelmanzer** [google/EXEgesis#8]
Hello, 

I was very excited to discover the Exegesis repo and am eager to try it out. I have followed the instructions given in the root README.md file, but I noticed that the resulting output file /tmp/intel_isa.pbtxt does not include any of the latency related fields given in this .proto file (such as min_latency, max_latency, etc):

https://github.com/google/EXEgesis/blob/master/exegesis/proto/instructions.proto

If anyone could kindly provide an example command that populates these fields, I would sincerely appreciate it. 

I apologize for posting this as an issue when it might be more appropriate for the @googlegroups list, but my email to that list bounced.

**Comment by legrosbuffle** [comment]
The tool that computes this information is:
https://github.com/google/EXEgesis/blob/master/exegesis/tools/compute_itineraries.cc

That being said, we have open-sourced a better tool as part of LLVM: [llvm-exegesis](https://llvm.org/docs/CommandGuide/llvm-exegesis.html). Further development will happen there.

**Comment by Artoria2e5** [comment]
It might be a good idea to put a link to the new LLVM tool in README, so that people are aware of the status of this repo.

**Comment by ondrasej** [comment]
Actually, we used to fill these fields by parsing the Intel Optimization Reference Manual, but this code was never open-sourced, and we've decided to retire it in favor of llvm-exegesis and @legrosbuffle mentioned.

We've removed these fields completely a recent update.
